###
POST http://localhost:3000/groups/1/records
Content-Type: application/json

{
  "exerciseType": "RUN",
  "description": "string",
  "time": 1,
  "distance": 1,
  "photos": [
    "string"
  ],
  "authorNickname": "길동",
  "authorPassword": "password123"
}
